* First message
Le : 24 avril 2018 à 11:09 (GMT +02:00)

De : "Jules" <jules.hernandez-sanchez@roche.com>À : "brice.ozenne@orange.fr" <brice.ozenne@orange.fr>, "Marc Buyse" <marc.buyse@iddi.com>, "Robbie Burnby" <robbie.burnby@roche.com>

Dear Brice and Marc, For some reason, bootstrapping does not work.
The message is

A bit of search took me to this places but don't understand the
problem or the solution (which does not work)

https://github.com/isaactpetersen/FantasyFootballAnalyticsR/issues/24
https://support.rstudio.com/hc/en-us/community/posts/202829578-Startup-error

I had to install "FootballAnalyticsR", and I don't even like football
;-) Any idea what's going on?

PS I'm attaching in this email a colleague that is experimenting with your package too

-- 

Jules Hernandez-Sanchez

Statistician, Biometrics (PDB)


Roche Products Limited 

6 Falcon Way 

Shire Park

Welwyn Garden City 

AL7 1TW 

Phone: +44(0)1707 366555

Fax: +44(0)1707 384513 


Working hours 09.00-17:00


Upcoming absences:

Registered in England No. 100674

The information transmitted in this message is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you receive this message in error, please contact the sender and delete the material from any computer.

Please consider the environment before printing this email

* Answer

On 25 April 2018 at 08:38, brice <brice.ozenne@orange.fr> wrote:

    Dear Jules,

    Thank you for report the error. The error message is also bit obscure for me.
    Nevertheless, since it mention "[tcl]", it could be a problem with the tcltk package that is used to display a progress bar when performing the resampling.
    Could you try again setting the argument trace to FALSE?

    I agree it's weird to have to install "FootballAnalyticsR"! BuyseTest does not depend on this package.
    What could have happened is that the tcltk library was not available and installing FootballAnalyticsR installed it.
    To check whether tcltk is correctly installed you can look at the section 4.6 at https://cran.r-project.org/bin/windows/base/rw-FAQ.html.
    (because on some platforms tcltk may not be available, I don't want BuyseTest to require tcltk to be installed)
        
    If this does not solve the problem, could you give me the output of:
    > sessionInfo()
    and the R code that would enable me to the error on my computer

    Finally, note that you can also report the issue on https://github.com/bozenne/BuyseTest/issues
    so that we keep track of it, and other users can see it.

    Best regards,
    Brice

* Second message

Le : 25 avril 2018 à 10:06 (GMT +02:00)
De : "Jules" <jules.hernandez-sanchez@roche.com>
À : "brice" <brice.ozenne@orange.fr>
Cc : "Marc Buyse" <marc.buyse@iddi.com>, "Robbie Burnby" <robbie.burnby@roche.com>, "julien peron" <julien.peron@ymail.com>
Objet : Re: Issue BuyseTest - bootstrap



Dear Brice,
When I set trace=0 the bootstrap works. But it didn't yesterday (?)
It does not work with trace >0

This is what I do:
d_Gehan <- BuyseTest(data=d,endpoint="time",treatment="arm",strata=NULL,type="timeToEvent",censoring="status",threshold=0,n.bootstrap=1000,method="Gehan",cpus=1,trace=0)
I attach the simulated data set too.
Thanks for helping
Jules

* Answer

On 25 April 2018 at 15:29, brice <brice.ozenne@orange.fr> wrote:

    Good. So it is likely to be related to the tcltk package.

    Can you try to run the following code in R:
    > library(tcltk)
    > demo(tkdensity)
    > demo(tkttest) 

    Normally it should display something like the picture (debug.png) in attachment.
    If tcltk is not properly installed or if your server does not support graphical output (like the linux server of my university) you may get what is in the file error-tcltk.txt

    I'm just a user of tcltk, so I unfortunately can't help you much with this package.
    As mentioned in the R documentation [1]: "This [have Tcl/Tk installed] is part of the R installation, so it should be there."
    Maybe try to install the latest version of R and check again what  demo(tkdensity) returns.

    Keep in mind that this won't affect the results of BuyseTest.
    It's just that you won't get a progress bar when performing the resampling.


    [1] https://cran.r-project.org/bin/windows/base/rw-FAQ.html#Package-TclTk-does-not-work_002e

* Third message
Le : 25 avril 2018 à 16:56 (GMT +02:00)
De : "Jules" <jules.hernandez-sanchez@roche.com>
À : "brice" <brice.ozenne@orange.fr>
Cc : "robbie burnby" <robbie.burnby@roche.com>
Objet : Re: RE : Re: Issue BuyseTest - bootstrap



Dear Brice,
The first time I loaded TclTk it gave me an error
The second time it didn't.
However, none of the demos worked, so didn't see anything like you show here.
A further error when pressing intro (yes, it asked me to press to see the demo) was the following:


I think our sever does not allow that behaviour.
Nothing to worry about but maybe you could add a note in the help material about setting trace=0 when this problem arises?
Thanks for your help
jules

* Answer

Sure, that's a good idea.
I will put that in the package BuyseTest package, under the heading "known issues".
in the next version (planned to be on CRAN in one or two weeks).

Thank you,
Brice

* Fouth message

and maybe set the trace default to 0?
Kind regards
jules

