
* First email

Le : 05 avril 2018 à 14:57 (GMT +02:00)
De : "joris.giai@chu-lyon.fr" <joris.giai@chu-lyon.fr>
À : "brice.ozenne@orange.fr" <brice.ozenne@orange.fr>
Objet : Problème nouvelle version BuyseTest


salut Brice,

j'espère que tout va pour le mieux pour toi depuis notre entrevue éclair à la thèse de Ceren.

Je te remets ci-joint le souci que j'ai avec BuyseTest
(une capture avec la version CRAN 1.0 et une autre avec la version github 1.1)
Ce serait super si tu pouvais débugger ça parce que je t'avoue que je m'y perds avec le code C...

En gros il semble que sur la version updatée (1.1) de BuyseTest, disponible sur github il y ait un problème avec la gestion des paires non-informatives : elle ne transfère jamais les non informatifs à l'outcome suivant alors que cela devrait du coup toujours être le cas, quelle que soit l’option choisie pour "neutralAsUninf".

Si on regarde la capture de la 1.1 :
- neutralAsUninf=TRUE : on voit 29.29% de paires qui arrivent au niveau du 2e outcome, alors qu'on en voudrait 29.29% + 2.91% =32.2%
- neutralAsUninf=FALSE : on voit 0% des paires qui arrivent au niveau du 2e outcome, alors qu'on en voudrait 2.91%

Merci d'avance +++, et dis moi si c'est pas clair

Joris


* Second email

De : GIAI, Joris
Envoyé : lundi 16 avril 2018 16:29
À : 'brice'
Cc : 'MAUCORT-BOULCH, Delphine (delphine.maucort-boulch@chu-lyon.fr)'; Julien Peron
Objet : RE: RE : Problème nouvelle version BuyseTest



pas de souci !

 

en pj :

- testBT.r : le code R pour générer un data de 6 patients puis analyse buysetest selon v1.0 ou v1.1 (changer les répertoires bien sur)

- les deux autres fichiers .r : un petit truc cool que je suis en train de faire : généraliser les comparaisons par paires au cas >2 traitements.

 

C'est pas forcément codé dans les règles de l'art (mais ça marche), mais l'idée est que si on a par exemple 3 traitements chez 3*50 personnes alors on forme les 50^3=125000 triplets possibles , qu'on doit ensuite comparer.

 

Ca fonctionne en théorie pour un nombre infini de traitements, en pratique il faut bien le coder sinon on sature vite la ram (et encore plus vite le proc)

 

Généraliser la paire au triplet c'est en fait dire : je mets +1 au meilleur traitement des 3 du triplet, je mets -1 au pire et je mets zéro au central (ou à tous les centraux qui ne sont ni le meilleur ni le pire pour les n-uplets).

 

A la fin au lieu d'avoir une seule valeur de net benefit (Delta) on en a une par traitement.

 

Dans le cas particulier de la paire, les deux Deltas obtenus somment à zéro en l'absence de paire neutre et on ne montre donc que le Delta du nouveau traitement par rapport à la référence : c'est les GPC classiques.

 

Dans le cas des n-uplets, on montre le Delta de chaque traitement et en l'absence de paire neutre ils somment également à zéro.

 

On peut ensuite faire de la rerandomisation selon nos envies les plus folles (non implémenté) :

- les comparer deux à deux en faisant la différence entre deux Deltas de deux traitements différents, puis tester la différence à zéro.

- les afficher tels quels avec leurs intervalles de confiance

 

Pour le moment ce n'est codé que pour du continu ou du binaire (le seuil doit être fixé manuellement à 0.5), donc pas de survie.

Mais c'était motivé par mon essai sur le syndrome de Raynaud en crossover multiple dans lequel les outcomes sont rapportés par les patients eux mêmes, or dans ce genre d'essais on n'a pas vraiment d'outcomes de survie.

 

On pourrait imaginer intégrer les outcomes type survie dedans :

- pour les essais en >2 bras parallèles utilisant OS et PFS

- pour comparer indirectement les différents essais en 2 bras dans le cancer du pancréas métastatique (clin d'oeil à Julien)

 

Voilà j'ai d'autres chats à fouetter et j'ai notamment promis des articles à mes directeurs de thèse mais je voulais vous informer de ce "petit" travail en plus.

Et si Brice tu t'ennuies, sens-toi libre d'implémenter ces uplets dans BuyseTest afin d'en faire des "Generalized Upletwise Comparisons" (GUC) ;)

 

a+

joris

* Last email

Le : 16 avril 2018 à 16:56 (GMT +02:00)
De : "joris.giai@chu-lyon.fr" <joris.giai@chu-lyon.fr>
À : "brice.ozenne@orange.fr" <brice.ozenne@orange.fr>, "julien.peron@ymail.com" <julien.peron@ymail.com>
Objet : RE: Buyse test - documentation on Github


génial merci ++

 

En tout cas maintenant on dirait que tu as bien corrigé le bug d'après ton readme (je ne peux pas telecharger sur github du boulot à cause de restrictions donc je ne peux pas tester le package tout de suite...)

 

tiens moi au courant de ce que tu penses de ma tentative de généralisation des GPC

 

à bientôt

 

Joris
